# -*- coding: utf-8 -*-
"""Untitled40.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/14ZbFqWWbhFY25a3jhHpBWLwrvzWFxhq2
"""

import pandas as pd
import numpy as np
from sklearn.preprocessing import StandardScaler

# --------------------------------------------------
# 1. Load the dataset
# --------------------------------------------------

data = pd.read_csv("Titanic.csv")

print("Original Dataset")
print(data.head())

# --------------------------------------------------
# 2. Dataset inspection
# --------------------------------------------------

print("\nNumber of Rows and Columns:")
print(data.shape)

print("\nColumn Information:")
data.info()

print("\nStatistical Summary:")
print(data.describe())

# --------------------------------------------------
# 3. Find missing values
# --------------------------------------------------

print("\nNull Values:")
print(data.isnull().sum())

# --------------------------------------------------
# 4. Handle missing values
# --------------------------------------------------

data["Age"] = data["Age"].fillna(data["Age"].median())

data["Fare"] = data["Fare"].fillna(data["Fare"].median())

data["Embarked"] = data["Embarked"].fillna(
    data["Embarked"].value_counts().index[0]
)

# --------------------------------------------------
# 5. Remove unnecessary column
# --------------------------------------------------

if "Cabin" in data.columns:
    data.drop("Cabin", axis=1, inplace=True)

# --------------------------------------------------
# 6. Remove duplicate rows
# --------------------------------------------------

data = data.drop_duplicates()

# --------------------------------------------------
# 7. Outlier treatment using IQR
# --------------------------------------------------

Q1 = data["Fare"].quantile(0.25)
Q3 = data["Fare"].quantile(0.75)

IQR = Q3 - Q1

lower_limit = Q1 - 1.5 * IQR
upper_limit = Q3 + 1.5 * IQR

data = data[
    (data["Fare"] >= lower_limit) &
    (data["Fare"] <= upper_limit)
]

# --------------------------------------------------
# 8. One-hot encoding
# --------------------------------------------------

data = pd.get_dummies(
    data,
    columns=["Sex", "Embarked"],
    drop_first=True,
    dtype=int
)

# --------------------------------------------------
# 9. Feature scaling
# --------------------------------------------------

scaler = StandardScaler()

data[["Age", "Fare"]] = scaler.fit_transform(
    data[["Age", "Fare"]]
)

# --------------------------------------------------
# 10. Display processed data
# --------------------------------------------------

print("\nProcessed Dataset:")
print(data.head())

print("\nFinal Shape:")
print(data.shape)

print("\nMissing Values After Preprocessing:")
print(data.isnull().sum())